services:
  - type: web
    name: backend-api
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    plan: starter

  - type: web
    name: frontend-dipendenti
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app_dipendenti.py --server.port 10000 --server.address 0.0.0.0
    plan: starter

  - type: web
    name: admin-dashboard
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run admin/app_admin.py --server.port 10000 --server.address 0.0.0.0
    plan: starter
